In [ ]:
import pandas as pd
import numpy as np


In [ ]:
dacta=pd.read_csv('/content/churn.csv')
data

year  customer_id  phone_no  gender  age  no_of_days_subscribed  \
0     2015       100198  409-8743  Female   36                     62   
1     2015       100643  340-5930  Female   39                    149   
2     2015       100756  372-3750  Female   65                    126   
3     2015       101595  331-4902  Female   24                    131   
4     2015       101653  351-8398  Female   40                    191   
...    ...          ...       ...     ...  ...                    ...   
1995  2015       997132  385-7387  Female   54                     75   
1996  2015       998086  383-9255    Male   45                    127   
1997  2015       998474  353-2080     NaN   53                     94   
1998  2015       998934  359-7788    Male   40                     94   
1999  2015       999961  414-1496    Male   37                     73   

     multi_screen mail_subscribed  weekly_mins_watched  minimum_daily_mins  \
0              no              no               148.35                12.2   
1              no              no               294.45                 7.7   
2              no              no                87.30                11.9   
3              no             yes               321.30                 9.5   
4              no              no               243.00                10.9   
...           ...             ...                  ...                 ...   
1995           no             yes               182.25                11.3   
1996           no              no               273.45                 9.3   
1997           no              no               128.85                15.6   
1998           no              no               178.05                10.4   
1999           no              no               326.70                10.3   

      maximum_daily_mins  weekly_max_night_mins  videos_watched  \
0                  16.81                     82               1   
1                  33.37                     87               3   
2                   9.89                     91               1   
3                  36.41                    102               4   
4                  27.54                     83               7   
...                  ...                    ...             ...   
1995               20.66                     97               5   
1996               30.99                    116               3   
1997               14.60                    110              16   
1998               20.18                    100               6   
1999               37.03                     89               6   

      maximum_days_inactive  customer_support_calls  churn  
0                       4.0                       1    0.0  
1                       3.0                       2    0.0  
2                       4.0                       5    1.0  
3                       3.0                       3    0.0  
4                       3.0                       1    0.0  
...                     ...                     ...    ...  
1995                    4.0                       2    NaN  
1996                    3.0                       1    0.0  
1997                    5.0                       0    0.0  
1998                    NaN                       3    0.0  
1999                    3.0                       1    1.0  

[2000 rows x 16 columns]

In [ ]:
data.dropna(axis=0,inplace=True)
data


year  customer_id  phone_no  gender  age  no_of_days_subscribed  \
0     2015       100198  409-8743  Female   36                     62   
1     2015       100643  340-5930  Female   39                    149   
2     2015       100756  372-3750  Female   65                    126   
3     2015       101595  331-4902  Female   24                    131   
4     2015       101653  351-8398  Female   40                    191   
...    ...          ...       ...     ...  ...                    ...   
1990  2015       993714  364-1969    Male   32                     61   
1991  2015       993815  387-5891    Male   49                     50   
1992  2015       994954  329-3222  Female   42                    119   
1996  2015       998086  383-9255    Male   45                    127   
1999  2015       999961  414-1496    Male   37                     73   

     multi_screen mail_subscribed  weekly_mins_watched  minimum_daily_mins  \
0              no              no               148.35                12.2   
1              no              no               294.45                 7.7   
2              no              no                87.30                11.9   
3              no             yes               321.30                 9.5   
4              no              no               243.00                10.9   
...           ...             ...                  ...                 ...   
1990           no              no                67.50                 9.8   
1991          yes             yes               460.65                 8.0   
1992           no             yes               176.70                 7.6   
1996           no              no               273.45                 9.3   
1999           no              no               326.70                10.3   

      maximum_daily_mins  weekly_max_night_mins  videos_watched  \
0                  16.81                     82               1   
1                  33.37                     87               3   
2                   9.89                     91               1   
3                  36.41                    102               4   
4                  27.54                     83               7   
...                  ...                    ...             ...   
1990                7.65                     94               6   
1991               52.21                    109               3   
1992               20.03                     76               3   
1996               30.99                    116               3   
1999               37.03                     89               6   

      maximum_days_inactive  customer_support_calls  churn  
0                       4.0                       1    0.0  
1                       3.0                       2    0.0  
2                       4.0                       5    1.0  
3                       3.0                       3    0.0  
4                       3.0                       1    0.0  
...                     ...                     ...    ...  
1990                    3.0                       2    0.0  
1991                    3.0                       0    0.0  
1992                    3.0                       3    0.0  
1996                    3.0                       1    0.0  
1999                    3.0                       1    1.0  

[1918 rows x 16 columns]

In [ ]:
data.isnull().sum()

year                      0
customer_id               0
phone_no                  0
gender                    0
age                       0
no_of_days_subscribed     0
multi_screen              0
mail_subscribed           0
weekly_mins_watched       0
minimum_daily_mins        0
maximum_daily_mins        0
weekly_max_night_mins     0
videos_watched            0
maximum_days_inactive     0
customer_support_calls    0
churn                     0
dtype: int64

In [ ]:
data.drop(['year','customer_id','phone_no','gender','multi_screen','mail_subscribed'], axis=1,inplace=True)
data.columns

Index(['age', 'no_of_days_subscribed', 'weekly_mins_watched',
       'minimum_daily_mins', 'maximum_daily_mins', 'weekly_max_night_mins',
       'videos_watched', 'maximum_days_inactive', 'customer_support_calls',
       'churn'],
      dtype='object')

In [ ]:
x=data.iloc[:,:-1].values
x

array([[ 36.  ,  62.  , 148.35, ...,   1.  ,   4.  ,   1.  ],
       [ 39.  , 149.  , 294.45, ...,   3.  ,   3.  ,   2.  ],
       [ 65.  , 126.  ,  87.3 , ...,   1.  ,   4.  ,   5.  ],
       ...,
       [ 42.  , 119.  , 176.7 , ...,   3.  ,   3.  ,   3.  ],
       [ 45.  , 127.  , 273.45, ...,   3.  ,   3.  ,   1.  ],
       [ 37.  ,  73.  , 326.7 , ...,   6.  ,   3.  ,   1.  ]])

In [ ]:
y=data.iloc[:,-1].values
y

array([0., 0., 1., ..., 0., 0., 1.])

In [ ]:
'''from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[3:8])], remainder= 'passthrough')
x=np.array(ct.fit_transform(x))'''

"from sklearn.compose import ColumnTransformer\nfrom sklearn.preprocessing import OneHotEncoder\nct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[3:8])], remainder= 'passthrough')\nx=np.array(ct.fit_transform(x))"

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=45)

In [ ]:
x_train

array([[ 58.  ,  61.  , 390.  , ...,   3.  ,   3.  ,   1.  ],
       [ 28.  , 112.  , 242.85, ...,   4.  ,   3.  ,   1.  ],
       [ 39.  ,  53.  ,  38.85, ...,   7.  ,   2.  ,   1.  ],
       ...,
       [ 31.  ,  69.  , 251.25, ...,   4.  ,   4.  ,   2.  ],
       [ 34.  , 106.  , 311.85, ...,   7.  ,   4.  ,   4.  ],
       [ 38.  ,  35.  , 158.4 , ...,   3.  ,   3.  ,   0.  ]])

In [ ]:
y_train

array([1., 0., 0., ..., 0., 0., 0.])

In [ ]:
from sklearn.preprocessing import StandardScaler
st_x= StandardScaler()
x_train= st_x.fit_transform(x_train)
x_test= st_x.transform(x_test)

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [ ]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[402  16]
 [ 51  11]]


0.8604166666666667

In [ ]:
from sklearn.metrics import classification_report
pred_lr = classifier.predict(x_test)

In [ ]:
print(classification_report(y_test,pred_lr))

              precision    recall  f1-score   support

         0.0       0.89      0.96      0.92       418
         1.0       0.41      0.18      0.25        62

    accuracy                           0.86       480
   macro avg       0.65      0.57      0.59       480
weighted avg       0.83      0.86      0.84       480

